version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    assignees:
      - "nicokempe"
    reviewers:
      - "nicokempe"
    commit-message:
      prefix: "[actions] "
  - package-ecosystem: "docker"
    directory: "/agent"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    assignees:
      - "nicokempe"
    reviewers:
      - "nicokempe"
    commit-message:
      prefix: "[docker] "
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    assignees:
      - "nicokempe"
    reviewers:
      - "nicokempe"
    commit-message:
      prefix: "[npm] "
  - package-ecosystem: "maven"
    directory: "/server"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    assignees:
      - "tylix"
    reviewers:
      - "tylix"
    commit-message:
      prefix: "[maven] "
  - package-ecosystem: "maven"
    directory: "/bot"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    assignees:
      - "tylix"
    reviewers:
      - "tylix"
    commit-message:
      prefix: "[maven] "
